"""empty message

Revision ID: 091d44a5d374
Revises: fa84bed8c80c
Create Date: 2022-03-11 10:07:52.306964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091d44a5d374'
down_revision = 'fa84bed8c80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('milk_sale_transaction_code_fkey', 'milk_sale', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('milk_sale_transaction_code_fkey', 'milk_sale', 'transactions', ['transaction_code'], ['transaction_code'])
    # ### end Alembic commands ###
