"""empty message

Revision ID: 32baf4750b29
Revises: 952c42c00aa2
Create Date: 2022-04-05 10:51:22.697175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32baf4750b29'
down_revision = '952c42c00aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('farmer_id', sa.Integer(), nullable=True))
    op.add_column('approvals', sa.Column('transaction_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approvals', 'transaction_code')
    op.drop_column('approvals', 'farmer_id')
    # ### end Alembic commands ###
