"""empty message

Revision ID: 483325663e6e
Revises: 
Create Date: 2022-03-10 09:17:09.189565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483325663e6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milk_total', sa.Column('carried_foward', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milk_total', 'carried_foward')
    # ### end Alembic commands ###
