"""empty message

Revision ID: 922c94aa01e7
Revises: c3ecd253939b
Create Date: 2022-04-05 12:23:59.385058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922c94aa01e7'
down_revision = 'c3ecd253939b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('farmer_ids', sa.String(), nullable=True))
    op.drop_column('approvals', 'farmer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('approvals', 'farmer_ids')
    # ### end Alembic commands ###
