"""empty message

Revision ID: 952c42c00aa2
Revises: 091d44a5d374
Create Date: 2022-04-04 17:51:38.841223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952c42c00aa2'
down_revision = '091d44a5d374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('appproval_id', sa.String(), nullable=False),
    sa.Column('cow_tag_id', sa.String(), nullable=False),
    sa.Column('cow_breed', sa.String(), nullable=False),
    sa.Column('cow_gender', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('admin_national_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('cow_image', sa.String(), nullable=False),
    sa.Column('cow_status', sa.Boolean(), nullable=False),
    sa.Column('cow_price', sa.Integer(), nullable=True),
    sa.Column('meat', sa.Boolean(), nullable=False),
    sa.Column('milk', sa.Boolean(), nullable=False),
    sa.Column('pregnant', sa.Boolean(), nullable=False),
    sa.Column('sold', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['admin_national_id'], ['admins.national_id'], ),
    sa.PrimaryKeyConstraint('appproval_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approvals')
    # ### end Alembic commands ###
