"""empty message

Revision ID: a0ad848bd2f3
Revises: d220fd9bfa67
Create Date: 2021-11-10 14:14:31.989446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ad848bd2f3'
down_revision = 'd220fd9bfa67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cowfeeds', sa.Column('food_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'cowfeeds', 'cowfeedinventory', ['food_name'], ['food_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cowfeeds', type_='foreignkey')
    op.drop_column('cowfeeds', 'food_name')
    # ### end Alembic commands ###
