"""empty message

Revision ID: c3ecd253939b
Revises: 32baf4750b29
Create Date: 2022-04-05 10:59:34.583570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ecd253939b'
down_revision = '32baf4750b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approvals', 'admin_national_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approvals', 'admin_national_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
