"""empty message

Revision ID: d220fd9bfa67
Revises: 
Create Date: 2021-11-10 14:09:05.578414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd220fd9bfa67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cowfeedinventory',
    sa.Column('feed_id', sa.String(), nullable=False),
    sa.Column('food_name', sa.String(), nullable=False),
    sa.Column('type_of_food', sa.String(), nullable=False),
    sa.Column('feed_quantity', sa.String(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('supplier_contact', sa.String(), nullable=False),
    sa.Column('admin_national_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_national_id'], ['admins.national_id'], ),
    sa.PrimaryKeyConstraint('feed_id'),
    sa.UniqueConstraint('food_name'),
    sa.UniqueConstraint('type_of_food')
    )
    op.create_table('cowfeeds',
    sa.Column('cow_feed_id', sa.String(), nullable=False),
    sa.Column('cow_tag_id', sa.String(), nullable=False),
    sa.Column('type_of_food', sa.String(), nullable=False),
    sa.Column('quantity_given', sa.String(), nullable=False),
    sa.Column('time_of_feeding', sa.String(), nullable=False),
    sa.Column('feeding_personel_id', sa.String(), nullable=False),
    sa.Column('admin_national_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_national_id'], ['admins.national_id'], ),
    sa.ForeignKeyConstraint(['cow_tag_id'], ['cowsinfo.cow_tag_id'], ),
    sa.ForeignKeyConstraint(['type_of_food'], ['cowfeedinventory.type_of_food'], ),
    sa.PrimaryKeyConstraint('cow_feed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cowfeeds')
    op.drop_table('cowfeedinventory')
    # ### end Alembic commands ###
