"""empty message

Revision ID: d7e9a9abad60
Revises: 922c94aa01e7
Create Date: 2022-04-05 12:24:27.883796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e9a9abad60'
down_revision = '922c94aa01e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('farmer_id', sa.String(), nullable=True))
    op.drop_column('approvals', 'farmer_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('farmer_ids', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('approvals', 'farmer_id')
    # ### end Alembic commands ###
