"""empty message

Revision ID: ec1efe994fab
Revises: a0ad848bd2f3
Create Date: 2021-11-10 15:00:44.678731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1efe994fab'
down_revision = 'a0ad848bd2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inseminations', sa.Column('insemination_officer_id', sa.Integer(), nullable=False))
    op.add_column('inseminations', sa.Column('insemination_officer_contact', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inseminations', 'insemination_officer_contact')
    op.drop_column('inseminations', 'insemination_officer_id')
    # ### end Alembic commands ###
