"""empty message

Revision ID: f01bfe8cfb99
Revises: 483325663e6e
Create Date: 2022-03-10 09:18:23.814321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01bfe8cfb99'
down_revision = '483325663e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('milk_total', 'carried_foward',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('milk_total', 'carried_foward',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
