"""empty message

Revision ID: fa84bed8c80c
Revises: f01bfe8cfb99
Create Date: 2022-03-10 19:25:13.815328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa84bed8c80c'
down_revision = 'f01bfe8cfb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cow_sales_transaction_code_fkey', 'cow_sales', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('cow_sales_transaction_code_fkey', 'cow_sales', 'transactions', ['transaction_code'], ['transaction_code'])
    # ### end Alembic commands ###
